[core] Fix "JavaScript heap out of memory" Error
The "Continuous Integration" and "Continuous Delivery" GitHub Actions
are currently not running successfully, because we get the following
error: "JavaScript heap out of memory"

To fix this error this commit increases the heap size to 4096 MB via the
NODE_OPTIONS environment variable
("NODE_OPTIONS=--max-old-space-size=4096") in the effected GitHub
Actions and the Docker image.